paragraphs_paste_third_party:
  type: mapping
  label: 'Schema for Paragraphs Paste options of Paragraphs Widget'
  mapping:
    enabled:
      type: boolean
      label: 'Copy & Paste area enabled'
    experimental:
      type: boolean
      label: 'Enable HTML processing (experimental).'
    property_path_mapping:
      type: sequence
      sequence:
        type: string
    split_method:
      type: mapping
      mapping:
        double_new_line:
          type: string
        regex:
          type: string
        url:
          type: string
    split_method_regex:
      type: string
      label: 'RegEx'

field.widget.third_party.paragraphs_paste:
  type: paragraphs_paste_third_party
